=== bibixx/zdaj-se-pjatk-data/schemas/subject-patch.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "subject-patch",
  "title": "Data Item",
  "type": "object",
  "properties": {
    "question": {
      "$id": "#root/question",
      "title": "Question",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": 0
    },
    "numberOfComments": {
      "$id": "#root/numberOfComments",
      "title": "Number of Comments",
      "type": "integer",
      "default": 0
    },
    "answers": {
      "$id": "#root/answers",
      "title": "Answers",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/answers/items",
        "title": "Items",
        "type": "object",
        "required": ["answer", "correct"],
        "properties": {
          "answer": {
            "$id": "#root/answers/items/answer",
            "title": "Answer",
            "type": "string",
            "default": ""
          },
          "correct": {
            "$id": "#root/answers/items/correct",
            "title": "Correct",
            "type": "boolean",
            "default": true
          },
          "isMarkdown": {
            "$id": "#root/answers/items/isMarkdown",
            "title": "Is Markdown",
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
          }
        },
        "required": ["author", "comment", "date"]
      }
    },
    "contributors": {
      "$id": "#root/contributors",
      "title": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "createdAt": {
      "$id": "#root/createdAt",
      "title": "Created At",
      "type": "integer",
      "default": 0
    },
    "isMarkdown": {
      "$id": "#root/isMarkdown",
      "title": "Is Markdown",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["question", "id", "createdAt"],
  "x-validate-file-id": "true"
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-116-7e263209-7662-45d0-82eb-739b5f8807de.patch.json
{
  "question": "The main reason for using ORM tools is to improve the performance of BD access.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "The basic premise of ORM is to make it easier (transparent) to work with any data source.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-116-7e263209-7662-45d0-82eb-739b5f8807de",
  "createdAt": 1691363367006
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/tin/z-02-bdecf51a-4dfd-4ece-81ea-2f4ad135070a.patch.json
{
  "question": "Język XSLT:",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "Zaimplementowano wyłącznie po stronie przeglądarki klienta",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "Wspiera rekurencyjne wywoływanie wzorców",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "Umożliwia przetwarzanie dowolnych dokumentów HTML",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "Działa wyłącznie po stronie serwera",
      "correct": false,
      "isMarkdown": false
    }
  ],
  "id": "z-02-bdecf51a-4dfd-4ece-81ea-2f4ad135070a",
  "createdAt": 1707434565194
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/aug/3476.patch.json
{
  "id": "3476",
  "question": "Czy dane stwierdzenie jest prawdziwe?",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "Determinizacja automatu skończonego może spowodować wykładniczą eksplozję liczby stanów.",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "Eliminacja ε-przejść w automacie skończonym prowadzi do automatu równoważnego automatowi wejściowemu.",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "Eliminacja ε-przejść w automacie skończonym może zmienić język akceptowany przez automat.",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "Eliminacja ε-przejść w automacie skończonym nie powoduje wzrostu liczby jego stanów.",
      "correct": true,
      "isMarkdown": false
    }
  ],
  "createdAt": 1751912300658,
  "$schema": "../../../schemas/subject-patch.json"
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-129-b020ee08-5b33-41eb-adef-bd3c9660ad98.patch.json
{
  "question": "One of the most important aspects of usability is the practical usefulness of the thing/service.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "Practical application is an important assessment factor.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-129-b020ee08-5b33-41eb-adef-bd3c9660ad98",
  "createdAt": 1691363367006
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/tin/3439.patch.json
{
  "id": "3439",
  "question": "Numery portów są przekazywane w ramach:",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "protokołu aplikacyjnego",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "protokołu warstwy sprzętowej",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "protokołu transportowego",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "protokołu warstwy sieciowej",
      "correct": false,
      "isMarkdown": false
    }
  ],
  "createdAt": 1738700523958,
  "$schema": "../../../schemas/subject-patch.json"
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/sbd/z-00-7816ffd8-3dac-4670-b743-2b5d7f0d9129.patch.json
{
  "question": "<strong>W których z wymienionych sytuacji mówimy o problemie fantomów?</strong>",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "Użytkownik zobaczył rekord wprowadzony przez innego użytkownika, który nie został zatwierdzony przez COMMIT",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "Rekord został w obrębie jednej transakcji wprowadzony (INSERT) i od razu usunięty (DELETE)",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "W trakcie działania transakcji inna transakcja wykonała INSERT",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "W trakcie działania transakcji inna transakcja wykonała DELETE",
      "correct": false,
      "isMarkdown": false
    }
  ],
  "id": "z-00-7816ffd8-3dac-4670-b743-2b5d7f0d9129",
  "createdAt": 1707647448640
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-02-a54e42d2-cdc1-432f-9200-acbd135ff49c.patch.json
{
  "question": "Classes in Java are presented directly.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "In Java, we have a special class keyword that allows direct creation of classes.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-02-a54e42d2-cdc1-432f-9200-acbd135ff49c",
  "createdAt": 1691363367006
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-155-064bbf65-e3de-4721-b2ed-705c849d6f24.patch.json
{
  "question": "The SwingWorker class displays the default version of the progress bar.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "The default implementation of the SwingWorker class does not contain any GUI elements.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-155-064bbf65-e3de-4721-b2ed-705c849d6f24",
  "createdAt": 1691363367006
}
