=== bibixx/zdaj-se-pjatk-data/schemas/subject.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1659129904.json",
  "title": "Root",
  "type": "object",
  "required": [
    "title",
    "id",
    "data",
    "updatedAt"
  ],
  "properties": {
    "title": {
      "$id": "#root/title",
      "title": "Title",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": ""
    },
    "data": {
      "$id": "#root/data",
      "title": "Data",
      "type": "array",
      "default": [],
      "items":{
        "$id": "#root/data/items",
        "title": "Items",
        "type": "object",
        "required": [
          "question",
          "id",
          "numberOfComments",
          "answers",
          "comments"
        ],
        "properties": {
          "question": {
            "$id": "#root/data/items/question",
            "title": "Question",
            "type": "string",
            "default": ""
          },
          "id": {
            "$id": "#root/data/items/id",
            "title": "Id",
            "type": ["integer", "null"],
            "default": 0
          },
          "numberOfComments": {
            "$id": "#root/data/items/numberOfComments",
            "title": "Numberofcomments",
            "type": "integer",
            "default": 0
          },
          "answers": {
            "$id": "#root/data/items/answers",
            "title": "Answers",
            "type": "array",
            "default": [],
            "items":{
              "$id": "#root/data/items/answers/items",
              "title": "Items",
              "type": "object",
              "required": [
                "answer",
                "correct"
              ],
              "properties": {
                "answer": {
                  "$id": "#root/data/items/answers/items/answer",
                  "title": "Answer",
                  "type": "string",
                  "default": ""
                },
                "correct": {
                  "$id": "#root/data/items/answers/items/correct",
                  "title": "Correct",
                  "type": "boolean",
                  "default": true
                }
              }
            }
          },
          "comments": {
            "$id": "#root/data/items/comments",
            "title": "Comments",
            "type": "array",
            "default": []
          }
        }
      }
    },
    "updatedAt": {
      "$id": "#root/updatedAt",
      "title": "Updatedat",
      "type": "integer",
      "default": 0
    }
  }
}

=== bibixx/zdaj-se-pjatk-data/aug.json
{
  "title": "Automaty i Gramatyki",
  "id": "aug",
  "data": [
    {
      "question": "<span>Dana jest relacja {(1,2),(2,3),(3,1),(2,4),(5,3)} określona na zbiorze {1,2,3,4,5,6}. Która z poniższych relacji stanowi jej&nbsp;</span><strong>domknięcie symetryczne</strong><span>?</span>",
      "id": 3088,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>{(1,2), (1,3), (2,1), (2,3), (2,4), (3,2), (3,5), (4,2)}</span>",
          "correct": false
        },
        {
          "answer": "<span>{(1,1), (1,2), (2,1), (2,3), (2,5), (3,1), (3,2), (3,5), (4,2), (5,3)}</span>",
          "correct": false
        },
        {
          "answer": "<span>{(1,2), (1,3), (2,1), (2,3), (2,4), (3,1), (3,2), (3,5), (4,2), (5,3)}</span>",
          "correct": true
        },
        {
          "answer": "<span>{(1,2), (1,3), (2,3), (2,4), (3,1), (3,2), (3,5), (5,3)}</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Czy dane stwierdzenie jest prawdziwe?",
      "id": 3476,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Determinizacja automatu skończonego może spowodować wykładniczą eksplozję liczby stanów.",
          "correct": true
        },
        {
          "answer": "Eliminacja ε-przejść w automacie skończonym prowadzi do automatu równoważnego automatowi wejściowemu.",
          "correct": true
        },
        {
          "answer": "Eliminacja ε-przejść w automacie skończonym może zmienić język akceptowany przez automat.",
          "correct": false
        },
        {
          "answer": "Eliminacja ε-przejść w automacie skończonym nie powoduje wzrostu liczby jego stanów.",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Czy dane stwierdzenie jest prawdziwe?",
      "id": 3477,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Lex/Flex generuje rodzaj automatu stosowego.",
          "correct": false
        },
        {
          "answer": "Zadaniem skanera jest podział tekstu wejściowego na leksemy.",
          "correct": true
        },
        {
          "answer": "Lex/Flex służy do tworzenia analizatorów leksykalnych (skanerów).",
          "correct": true
        },
        {
          "answer": "Lex/Flex generuje rodzaj automatu skończonego.",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Dana jest następująca gramatyka:<p></p>\n<p>S → aXS | bYS | ε<br>X → aXX | b<br>Y → bYY | a</p>\n<p>Język generowany przez tą gramatykę to:\n          </p>",
      "id": 3478,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Słowa zawierające tyle samo liter a i b",
          "correct": true
        },
        {
          "answer": "Słowa zawierające więcej liter a niż b",
          "correct": false
        },
        {
          "answer": "Pusty język",
          "correct": false
        },
        {
          "answer": "Palindromy nad alfabetem {a,b}",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1655414026990
}

=== bibixx/zdaj-se-pjatk-data/zpr.json
{
  "$schema":"schemas/subject.json",
  "title": "Zarządzanie projektem informatycznym (ZPR)",
  "id": "zpr",
  "data": [
    {
      "question": "<span>Która z cech nie jest charakterystyczna dla typowej działalności projektowej</span>",
      "id": 3192,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>zespołowość</span>",
          "correct": false
        },
        {
          "answer": "<span>planowanie</span>",
          "correct": false
        },
        {
          "answer": "<span>dążenie do przewidywalnego rezultatu</span>",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Które z określeń nie jest charakterystyczne dla działalności projektowe. Projekt jest</span>",
      "id": 3288,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>ukierunkowany na wytworzenie unikalnego produktu</span>",
          "correct": false
        },
        {
          "answer": "zawsze działalnością krytyczną dla przedsiębiorstwa",
          "correct": true
        },
        {
          "answer": "<span>działalnością czasową</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Wskaż zdania prawdziwe</span>",
      "id": 3289,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Na grafie precedensji nie można przedstawić zależności typu FS i FF między zadaniami",
          "correct": false
        },
        {
          "answer": "Graf precedensji przedstawia strukturę zadaniowo-czasową projektu",
          "correct": true
        },
        {
          "answer": "Zawsze dla diagramu Gantta można wykonać odpowiadający mu graf precedensji",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Twórcą map myśli jest",
      "id": 3290,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Covey",
          "correct": false
        },
        {
          "answer": "Eisenhauer",
          "correct": false
        },
        {
          "answer": "Buzan",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Jesteś kierownikiem projektu informatycznego. Twój kierownik ds. jakości poinformował Cię, że należy zakończyć planowanie testów oprogramowania tuż przed ich rozpoczęciem. Jednocześnie powinieneś rozpocząć testowanie produktów możliwie jak najpóźniej, aby uwzględnić wszystkie zmiany w nich zachodzące. Jaka wobec tego powinna by zależność między aktywnością polegającą na planowaniu testów a aktywnością polegającą na ich wykonaniu</span><em><span><br></span></em>",
      "id": 3291,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "FS",
          "correct": true
        },
        {
          "answer": "SF",
          "correct": false
        },
        {
          "answer": "SS",
          "correct": false
        },
        {
          "answer": "FF",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Które ze stwierdzeń dotyczących struktury podziału prac jest prawdziwe",
      "id": 3292,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "WBS przedstawia wszystkie zadania, które muszą by wykonane w projekcie",
          "correct": true
        },
        {
          "answer": "każdy element WBS reprezentuje cechę produktu projektu",
          "correct": false
        },
        {
          "answer": "WBS przedstawia pakiety prac uporządkowane w postaci liniowej, niestrukturalizowanej listy",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Który z obszarów klasyfikacyjnych ryzyka jest obszarem stosowanym w taksonomiach ryzyka projektów informatycznych",
      "id": 3293,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "założeń opłacalności",
          "correct": true
        },
        {
          "answer": "zewnętrznych zależności",
          "correct": true
        },
        {
          "answer": "techniczny",
          "correct": true
        },
        {
          "answer": "organizacyjny, planowania",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Procesy zarządzania projektem zdefiniowanie niezgodnie z PMBOK, to",
      "id": 3294,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "inicjacji, planowania, kontrolne, wykonawcze, testowania, końcowe",
          "correct": true
        },
        {
          "answer": "inicjacji, planowania, kontrolne, wykonawcze, końcowe",
          "correct": true
        },
        {
          "answer": "planowania, kontrolne, wykonawcze, końcowe",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1659128372196
}

=== bibixx/zdaj-se-pjatk-data/hur.json
{
  "$schema": "schemas/subject.json",
  "title": "Hurtownie danych i aplikacje OLAP",
  "id": "hur",
  "data": [
    {
      "question": "Różnica impedancji",
      "id": 2983,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "To obciążenie systemowe związane z wykonywaniem kodu SQL i próba pominięcia go lub zastąpienia w operacjach bazodanowych",
          "correct": false
        },
        {
          "answer": "To obciążenie systemowe powstające, gdy wykonany zostaje kod SQL zaszyty w kodzie napisanym w języku obiektowym",
          "correct": false
        },
        {
          "answer": "To dysonans między \"światem obiektowym\" a \"światem relacyjnym\"",
          "correct": true
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1690840372818
}

=== bibixx/zdaj-se-pjatk-data/skj.json
{
  "$schema": "schemas/subject.json",
  "title": "Sieci Komputerowe - ang - egzamin ",
  "id": "skj",
  "data": [
    {
      "question": "<span>TEMPEST protects against:</span>",
      "id": 2628,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>sniffing at link layer&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>sniffing at physical layer</span>",
          "correct": false
        },
        {
          "answer": "<span>spoofing at physical layer</span>",
          "correct": false
        },
        {
          "answer": "<span>TEMPEST is not a protection technology</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Processing a recursive DNS query, a contacted DNS server is responsible for providing the answer for the client. It may be necessary that the server communicates with other servers to get the asnwer.</span>",
      "id": 2629,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>No</span>",
          "correct": false
        },
        {
          "answer": "Yes",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<span>&nbsp;A protocol used to automatically configure IP networking for a host is called:</span>",
      "id": 2630,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>DNS&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>DHCP</span>",
          "correct": false
        },
        {
          "answer": "<span>SNMP</span>",
          "correct": false
        },
        {
          "answer": "<span>DHCM&nbsp;</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>If on one link, at the same time, in the same place and on the same frequency, multiple devices communicate, than what is the type of multiplexing used? Choose the acronym.</span>",
      "id": 2631,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>FDM</span>",
          "correct": false
        },
        {
          "answer": "<span>TDM&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>CDM</span>",
          "correct": true
        },
        {
          "answer": "<span>WDM</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "IPSec provides security in layer",
      "id": 2632,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "transport",
          "correct": false
        },
        {
          "answer": "network",
          "correct": true
        },
        {
          "answer": "application",
          "correct": false
        },
        {
          "answer": "link",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>&nbsp;How many bits are used in an IPv6 address</span>",
      "id": 2633,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>1024</span>",
          "correct": false
        },
        {
          "answer": "<span>128&nbsp;</span>",
          "correct": true
        },
        {
          "answer": "<span>64</span>",
          "correct": false
        },
        {
          "answer": "<span>256&nbsp;</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>&nbsp;Window mechanism is used in</span>",
      "id": 2634,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>TCP</span>",
          "correct": true
        },
        {
          "answer": "<span>OSPF</span>",
          "correct": false
        },
        {
          "answer": "<span>IP&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>UDP</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Internet telephony usually uses</span>",
      "id": 2635,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>HTTP</span>",
          "correct": false
        },
        {
          "answer": "<span>UDP</span>",
          "correct": true
        },
        {
          "answer": "<span>TCP</span>",
          "correct": false
        },
        {
          "answer": "<span>IPvoice</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>What services does an IP network offer for applications?&nbsp;</span>",
      "id": 2636,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>an unreliable \"best-effort\" service</span>",
          "correct": true
        },
        {
          "answer": "<span>a communication service with guaranteed minimal throughput</span>",
          "correct": false
        },
        {
          "answer": "<span>a reliable TCP service</span>",
          "correct": false
        },
        {
          "answer": "<span>a communication service with guaranteed upper bounds on delay</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>In the physical layer we are talking about (…)</span>",
      "id": 2637,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>frames&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>bits</span>",
          "correct": true
        },
        {
          "answer": "<span>segments&nbsp;</span><br><br>",
          "correct": false
        },
        {
          "answer": "packets",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "PGP używa kluczy:",
      "id": 2642,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "kluczy Geanta",
          "correct": false
        },
        {
          "answer": "żadna z pozostałych odpowiedzi nie jest poprawna",
          "correct": true
        },
        {
          "answer": "symetrycznych",
          "correct": false
        },
        {
          "answer": "jednokrotnych",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Co opisuje uzycie gniazd przez serwer w niezawodnej, połączeniowej komunikacji z klientem?",
      "id": 2643,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "gniazdo serwera rozpoczyna połączenie",
          "correct": false
        },
        {
          "answer": "serwer oczekuje połączeń od klientów",
          "correct": true
        },
        {
          "answer": "gniazdo klienta musi istnieć przed gniazdem serwera",
          "correct": false
        },
        {
          "answer": "port jednoznacznie determinuje gniazdo serwera",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Uwierzytelnianie ma na celu:",
      "id": 2644,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "potwierdzenie wiarygodności uzytkownika",
          "correct": false
        },
        {
          "answer": "sprawdzenie integralności przesyłanego komunikatu",
          "correct": false
        },
        {
          "answer": "sprawdzenie uprawnień użytkownika",
          "correct": false
        },
        {
          "answer": "sprawdzenie tożsamości użytkownika",
          "correct": true
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1668376740820
}

=== bibixx/zdaj-se-pjatk-data/mad.json
{
  "title": "Matematyka Dyskretna 2020",
  "id": "mad",
  "data": [
    {
      "question": "Jeżeli wiemy, że maszyna kapsułkująca podczas jednego cyklu produkcyjnego zacina się z prawdopodobieństwem 0.1, a w przeciągu dnia uruchamiamy 10 cykli produkcyjnych, to prawdą jest to, że:",
      "id": 3340,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Spodziewamy się jednego zacięcia",
          "correct": false
        },
        {
          "answer": "Spodziewamy się pierwszego zacięcia dopiero w ostatnim cyklu danego dnia",
          "correct": false
        },
        {
          "answer": "Spodziewamy się pięciu zacięć",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Na ile sposobów możemy rozdać 5 różnych książek trójce dzieci, tak aby każde z nich dostało co najmniej jedną książkę:",
      "id": 3341,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "3!*S(5,3)",
          "correct": false
        },
        {
          "answer": "2!*S(5,2)",
          "correct": false
        },
        {
          "answer": "5!*S(3,2)",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Zbiorem potęgowym zbioru {<span>∅</span>} jest:",
      "id": 3342,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "{<span>∅</span>,{<span>∅</span>}}",
          "correct": true
        },
        {
          "answer": "{<span>∅</span>}",
          "correct": false
        },
        {
          "answer": "{{<span>∅</span>}}",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Które z poniższych zbiorów są równoliczne z zbiorem liczb naturalnych:",
      "id": 3343,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "R",
          "correct": false
        },
        {
          "answer": "Zbiór liczb pierwszych",
          "correct": false
        },
        {
          "answer": "{1,5,2,6}",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Jeżeli nieprawdą jest że wszyscy wysocy ludzię są inteligentni to wiemy, że prawdą jest:",
      "id": 3344,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Niscy ludzie są inteligentni",
          "correct": false
        },
        {
          "answer": "Wysocy ludzie nie są inteligentni",
          "correct": false
        },
        {
          "answer": "Wzrost nie pozwala na jednoznaczne wnioskowanie o inteligencji",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Iluzjonista wydobył z pięciu różnych cylindrów pięć różnych przedmiotów. Po prezentacji włożył je losowo po jednym do cylindra. Na ile sposobów mógł to zrobić, jeśli żaden przedmiot nie trafił do cylindra w którym był?",
      "id": 3345,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "196",
          "correct": false
        },
        {
          "answer": "25",
          "correct": false
        },
        {
          "answer": "55",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Do zdań, dla których do określenia wartości wystarczy analiza syntaksuczna należą",
      "id": 3346,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Zdania złożone",
          "correct": false
        },
        {
          "answer": "Zdania sprzeczne",
          "correct": false
        },
        {
          "answer": "Zdania proste",
          "correct": false
        },
        {
          "answer": "Zadne&nbsp;",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Wariancja zmiennej losowej zawsze",
      "id": 3382,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "jest dodatnia,",
          "correct": false
        },
        {
          "answer": "należy do zakresu [0,1],",
          "correct": false
        },
        {
          "answer": "jest nieujemna.",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Liczba podzbiorów zbioru {A,B,C,D,E} o parzystej liczbie elementów jest:",
      "id": 3383,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "równa 16",
          "correct": false
        },
        {
          "answer": "parzysta",
          "correct": true
        },
        {
          "answer": "równa 20",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Relacja określona następująco: R = { (x,y)&nbsp;<span>∈</span>&nbsp;R x R: ( x*y = 1) } jest",
      "id": 3384,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "funkcją częściową",
          "correct": true
        },
        {
          "answer": "asymetryczna",
          "correct": true
        },
        {
          "answer": "funkcja całkowitą",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1655414080603
}

=== bibixx/zdaj-se-pjatk-data/modeling_and_analysis_of_it_systems.json
{
  "$schema": "schemas/subject.json",
  "title": "Modeling and Analysis of IT Systems",
  "id": "modeling_and_analysis_of_it_systems",
  "data": [
    {
      "question": "Assosiations can be directly implemented in Java",
      "id": 3628,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": false
        },
        {
          "answer": "No",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Associations from the object model are implemented as tables in the relational mode",
      "id": 3629,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": false
        },
        {
          "answer": "No",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Directional associations are always more useful than bidirectional associations",
      "id": 3630,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": false
        },
        {
          "answer": "No",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "An association is a group of connections within the same semantics and structure",
      "id": 3631,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": true
        },
        {
          "answer": "No",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1690840372818
}
