=== bibixx/zdaj-se-pjatk-data/schemas/subject-patch.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "subject-patch",
  "title": "Data Item",
  "type": "object",
  "properties": {
    "question": {
      "$id": "#root/question",
      "title": "Question",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": 0
    },
    "numberOfComments": {
      "$id": "#root/numberOfComments",
      "title": "Number of Comments",
      "type": "integer",
      "default": 0
    },
    "answers": {
      "$id": "#root/answers",
      "title": "Answers",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/answers/items",
        "title": "Items",
        "type": "object",
        "required": ["answer", "correct"],
        "properties": {
          "answer": {
            "$id": "#root/answers/items/answer",
            "title": "Answer",
            "type": "string",
            "default": ""
          },
          "correct": {
            "$id": "#root/answers/items/correct",
            "title": "Correct",
            "type": "boolean",
            "default": true
          },
          "isMarkdown": {
            "$id": "#root/answers/items/isMarkdown",
            "title": "Is Markdown",
            "type": "boolean",
            "default": false
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "author": {
            "type": "string"
          },
          "comment": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
          }
        },
        "required": ["author", "comment", "date"]
      }
    },
    "contributors": {
      "$id": "#root/contributors",
      "title": "Contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "createdAt": {
      "$id": "#root/createdAt",
      "title": "Created At",
      "type": "integer",
      "default": 0
    },
    "isMarkdown": {
      "$id": "#root/isMarkdown",
      "title": "Is Markdown",
      "type": "boolean",
      "default": false
    }
  },
  "required": ["question", "id", "createdAt"],
  "x-validate-file-id": "true"
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/sbd2015/2960.patch.json
{
  "id": "2960",
  "question": "Które z poniższych stwierdzeń jest prawdziwe w T-SQL",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "W procedurze mogą być wykonywane polecenia DQL",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "W procedurze mogą być wykonywane polecenia DDL",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "W procedurze mogą być wykonywane polecenia DML",
      "correct": true,
      "isMarkdown": false
    },
    {
      "answer": "W procedurach T-SQL można używać parametrów",
      "correct": true,
      "isMarkdown": false
    }
  ],
  "createdAt": 1725264745813,
  "$schema": "../../../schemas/subject-patch.json"
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/sbd/01_3475.patch.json
{
  "question": "<strong>Które z wymienionych instrukcji PL/SQL prawidłowo zadeklarują zmienną (zmienne) w PL/SQL ?</strong>",
  "id": "3475",
  "comments": [
    {
      "author": "Ola",
      "comment": "Pierwsza i druga odpowiedź niepoprawne, w PL/SQL nie ma typu INT.\nTrzecia odpowiedź niepoprawna, kolumna sal nie ma przydzielonej tabeli.\nPoprawna odpowiedź: DECLARE v_ile emp.sal%TYPE; (załącznik uzasadnienie 1.)\n\nUzasadnienie\nZ prezentacji PL SQL cz.1\nZmienne wierszowe %ROWTYPE\nWzorcem dla deklarowanej zmiennej może być cały wiersz, albo instrukcja\nSELECT definiująca kursor. Na zmienną podstawiana jest wówczas cała zawartość\nrekordu, a odczyt wartości z poszczególnych pól odbywa się poprzez odwołanie:\nnazwa_zmiennej.nazwa_kolumny\nZmiennej wierszowej nie można użyć bezpośrednio po słowie kluczowym VALUES\nw instrukcji INSERT INTO.\nPrzykład :\nDECLARE\nv_test emp%rowtype; v_ename emp.ename%type;\nv_sal emp.sal%type;\nBEGIN\nSELECT * INTO v_test FROM emp WHERE empno = 7788;\nv_ename := v_test.ename;\nv_sal := v_test.sal;\ndbms_output.put_line(v_ename || ‘ zarabia ‘ || v_sal);\nEND;\n",
      "date": "29-07-2021 13:06:00"
    }
  ],
  "answers": [
    {
      "answer": "DECLARE<br>&nbsp; &nbsp; v_ala Varchar2(10);<br>&nbsp; &nbsp; v_ile Int; v_data Date;<br>BEGIN<p></p>\n<p>...</p>",
      "correct": false
    },
    {
      "answer": "DECLARE v_ile INT:=0;",
      "correct": false
    },
    {
      "answer": "DECLARE v_ile sal%TYPE;",
      "correct": false
    },
    {
      "answer": "DECLARE v_ile emp.sal%TYPE;",
      "correct": true
    }
  ],
  "createdAt": 1707647448640
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/tak_ang/z-00-a3a62cc0-d051-427f-b892-4f4068f588e6.patch.json
{
  "question": "<span lang=\"EN-US\">In 8-bit code the signed number representation</span>",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "<span lang=\"EN-US\">11111111 represents value 0</span>",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "<span lang=\"EN-US\">11110000 represents value -16</span>",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "<span lang=\"EN-US\">11110000 represents value -15</span>",
      "correct": false,
      "isMarkdown": false
    }
  ],
  "id": "z-00-a3a62cc0-d051-427f-b892-4f4068f588e6",
  "createdAt": 1676212387535
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-47-30cc4f31-b1cd-4dc1-8ae9-0ceb37154e38.patch.json
{
  "question": "Associations in the superclass are not inherited.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": false
    },
    {
      "answer": "No",
      "correct": true
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "All invariants (including associations) are inherited by a subclass.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-47-30cc4f31-b1cd-4dc1-8ae9-0ceb37154e38",
  "createdAt": 1691363367006
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/tin/2155.patch.json
{
  "id": "2155",
  "question": "Wyrażenie &lt;!-- &nbsp;--&gt; w dokumencie XML sklasyfikujemy jako:",
  "isMarkdown": false,
  "answers": [
    {
      "answer": "Deklarację XML",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "Instrukcję przetwarzania",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "Encję parametryczną",
      "correct": false,
      "isMarkdown": false
    },
    {
      "answer": "Element tekstowy",
      "correct": true,
      "isMarkdown": false
    }
  ],
  "createdAt": 1738575570749,
  "$schema": "../../../schemas/subject-patch.json"
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/abd/z-11-3cf02271-1613-4823-8992-72325d10755d.patch.json
{
  "question": "Wybierz poprawne stwierdzenia dotyczące konfiguracji typu \"log shipping\" w MS SQL Server:",
  "isMarkdown": true,
  "comments": [],
  "answers": [
    {
      "answer": "W konfiguracji typu \"log shipping\" może istnieć tylko jeden serwer zapasowy powiązany z jednym serwerem głównym.",
      "correct": false
    },
    {
      "answer": "W konfiguracji typu \"log shipping\" możliwa jest praca z zapasową bazą danych, ale tylko do odczytu.",
      "correct": false
    },
    {
      "answer": "W konfiguracji typu \"log shipping\" możliwa jest praca z zapasową bazą danych włącznie z wprowadzaniem do niej zmian.",
      "correct": false
    },
    {
      "answer": "W konfiguracji typu \"log shipping\", gdy wprowadzimy modyfikację do tabeli na serwerze zapasowym, to ta modyfikacja zostanie automatycznie przeniesiona na serwer główny przy pomocy rozproszonej transakcji.",
      "correct": false
    }
  ],
  "id": "z-11-3cf02271-1613-4823-8992-72325d10755d",
  "createdAt": 1657199812909
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/abd/z-04-e464ab22-fdee-4794-bd62-2458e3320e86.patch.json
{
  "question": "Wskaż poprawne stwierdzenia dotyczące kont logowania (logins) i użytkowników (users) w MS SQL Server:",
  "isMarkdown": true,
  "comments": [],
  "answers": [
    {
      "answer": "Dla konta logowania (login) możemy bezpośrednio przypisać prawo SELECT do tabeli.",
      "correct": false
    },
    {
      "answer": "Dla użytkownika (user) możemy bezpośrednio przypisać prawo SELECT do tabeli",
      "correct": false
    },
    {
      "answer": "Konto logowania (login) jest zawsze tworzone dla jednej bazy danych",
      "correct": false
    },
    {
      "answer": "Użytkownik (user) jest zawsze tworzony dla jednej bazy danych",
      "correct": false
    }
  ],
  "id": "z-04-e464ab22-fdee-4794-bd62-2458e3320e86",
  "createdAt": 1657199812909
}

=== bibixx/zdaj-se-pjatk-data/overrides/patches/modeling_and_analysis_of_it_systems/z-71-9f62f8d7-3afc-46b2-a956-7b5af3baf18e.patch.json
{
  "question": "The {subset} implementation requires a method to check for the existence of a given link.",
  "numberOfComments": 1,
  "answers": [
    {
      "answer": "Yes",
      "correct": true
    },
    {
      "answer": "No",
      "correct": false
    }
  ],
  "comments": [
    {
      "author": "Samuele Milan",
      "comment": "One of the basic activities that needs to be done is to check the existence of a particular link.",
      "date": "02-09-2023 00:00:00"
    }
  ],
  "contributors": [
    "Samuele Milan"
  ],
  "id": "z-71-9f62f8d7-3afc-46b2-a956-7b5af3baf18e",
  "createdAt": 1691363367006
}
